update docker_check.yaml

diff --git a/.github/workflows/docker_check.yaml b/.github/workflows/docker_check.yaml
--- a/.github/workflows/docker_check.yaml
+++ b/.github/workflows/docker_check.yaml
@@ -44,31 +44,32 @@ jobs:
         id: trivy-scan
         uses: aquasecurity/trivy-action@0.28.0
         with:
-          image-ref: "${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
+          image-ref: "/files/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
           format: "json"
           output: "trivy-report.json"
 
-      - name: Read Trivy Report
-        id: read_trivy
-        run: |
-          if [ ! -f trivy-report.json ]; then
-            echo "Trivy report not found!"
-            exit 1
-          fi
-          echo "Trivy report found!"
-          cat trivy-report.json
-      # - name: Upload Docker Trivy Report
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: trivy-report
-      #     path: trivy-report.json
+      # - name: Read Trivy Report
+      #   id: read_trivy
+      #   run: |
+      #     if [ ! -f trivy-report.json ]; then
+      #       echo "Trivy report not found!"
+      #       exit 1
+      #     fi
+      #     echo "Trivy report found!"
+      #     cat trivy-report.json
+
+      - name: Upload Docker Trivy Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-report
+          path: trivy-report.json
 
       # - name: Read Trivy scan results
-      #   id: read_trivy_results
+      #   id: read_trivy_report
       #   run: |
-      #     SCAN_RESULTS=$(cat trivy-results.json)
-      #     echo "results<<EOF" >> $GITHUB_OUTPUT
-      #     echo "$SCAN_RESULTS" >> $GITHUB_OUTPUT
+      #     SCAN_REPORT=$(cat trivy-report.json)
+      #     echo "reports<<EOF" >> $GITHUB_OUTPUT
+      #     echo "$SCAN_REPORT" >> $GITHUB_OUTPUT
       #     echo "EOF" >> $GITHUB_OUTPUT
 
       - name: Update Pull Request
