update docker_check.yaml

diff --git a/.github/workflows/docker_check.yaml b/.github/workflows/docker_check.yaml
--- a/.github/workflows/docker_check.yaml
+++ b/.github/workflows/docker_check.yaml
@@ -48,15 +48,15 @@ jobs:
           format: "json"
           output: "trivy-report.json"
 
-      # - name: Read Trivy Report
-      #   id: read_trivy
-      #   run: |
-      #     if [ ! -f trivy-report.json ]; then
-      #       echo "Trivy report not found!"
-      #       exit 1
-      #     fi
-      #     echo "Trivy report found!"
-      #     cat trivy-report.json
+      - name: Read Trivy Report
+        id: read_trivy
+        run: |
+          if [ ! -f trivy-report.json ]; then
+            echo "Trivy report not found!"
+            exit 1
+          fi
+          echo "Trivy report found!"
+          cat trivy-report.json
 
       - name: Upload Docker Trivy Report
         uses: actions/upload-artifact@v4
